# Site settings
title: All Things Automation
description: 'with Edmund Dipple'
url: 'https://www.elmund.io'
baseurl: '/'
google_analytics: 'UA-64797721-1'
disqus_shortname: 'elmundio'

author:
  name: 'Edmund Dipple'
  email: elmundio1987@gmail.com
  twitter_username: elmundio87
  facebook_username: edmund.dipple
  github_username:  elmundio87
  linkedin_username:  edmund-dipple

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate','jekyll-redirect-from']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
